//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPABNBADMIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avi
    {
        public int idAvis { get; set; }
        public int idClient { get; set; }
        public int idHebergement { get; set; }
        public decimal Note { get; set; }
        public string Commentaire { get; set; }
        public bool Etat { get; set; }
    }
}
